version: "3"

tasks:
  # Client
  pull:
    cmds:
      - rclone sync onedrive-dev:/ ./onedrive-dev/ -P --filter-from client.rclonefilter --track-renames
  pull-full:
    cmds:
      - rclone sync onedrive-dev:/ ./onedrive-dev/ -P --filter-from server.rclonefilter --track-renames
  push:
    cmds:
      - rclone sync ./onedrive-dev/ onedrive-dev:/ -P --filter-from client.rclonefilter

  backup:
    cmd: node backup.js

  web:
    cmds:
      - rclone rcd --rc-web-gui

  export:
    cmds:
      - node export.js
  import:
    cmds:
      - node import.js
