version: "3"

dotenv: ['.env']

tasks:
  # Client
  pull:
    cmds:
      - rclone sync onedrive-dev:/ ./onedrive-dev/ -P --filter-from $CLIENT_FILTER_PATH --track-renames --bwlimit 5M --transfers 8
  pull-full:
    cmds:
      - rclone sync onedrive-dev:/ ./onedrive-dev/ -P --filter-from $CLIENT_FILTER_PATH --track-renames --bwlimit 5M --transfers 8
  push:
    cmds:
      - rclone sync ./onedrive-dev/ onedrive-dev:/ -P --filter-from $CLIENT_FILTER_PATH --transfers 8

  backup:
    cmd: node backup.js

  web:
    cmds:
      - rclone rcd --rc-web-gui

  export:
    cmds:
      - node export.js
  import:
    cmds:
      - node import.js
