version: "3"

dotenv: [".env"]

tasks:
  export:
    cmds:
      - node export.js
  import:
    cmds:
      - node import.js

  # Client
  web:
    cmds:
      - rclone rcd --rc-web-gui

  # Server
  backup:
    cmd: node server-backup.js
  install-service:
    cmds:
      - node install-service.js
  uninstall-service:
    cmds:
      - node uninstall-service.js

  # Desktop
  dev-app:
    cmds:
      - wails dev
    dir: desktop
  build-app-mac:
    platforms: [darwin]
    cmds:
      - wails build -v 2
      # - codesign --sign - --force --deep build/bin/desktop.app
      # - upx --best build/bin/desktop --force-macos
      # - chmod +x build/bin/desktop.app/Contents/MacOS/desktop
      - rm -rf ../desktop.app
      - mv build/bin/desktop.app ../desktop.app
      # - open ../desktop.app
    dir: desktop
  build-app-win:
    platforms: [windows]
    cmds:
      - wails build -v 2 # -windowsconsole to show the console for debugging
      - powershell.exe "Move-Item -Path ./build/bin/desktop.exe -Destination ../desktop.exe -Force"
    dir: desktop
