version: "3"

tasks:
  # Client
  tome:
    cmds:
      - rclone sync onedrive-dev:/ ./onedrive-dev/ -P --filter-from client.rclonefilter --track-renames
  topro:
    cmds:
      - rclone sync ./onedrive-dev/ onedrive-dev:/ -P --filter-from client.rclonefilter

  # Backup
  backup-onedrive:
    cmds:
      - rclone sync onedrive-dev:/ onedrive-dev-cript:/ -P --filter-from server.rclonefilter --backup-dir onedrive-dev-cript:/.rclone-backup/`date +%Y%m%d.%H%M%S`
  backup-dropbox:
    cmds:
      - rclone sync onedrive-dev:/ dropbox-cript:/ -P --filter-from server.rclonefilter --backup-dir dropbox-cript:/.rclone-backup/`date +%Y%m%d.%H%M%S`
  backup-yandex:
    cmds:
      - rclone sync onedrive-dev:/ yandex-cript:/ -P --filter-from server.rclonefilter --backup-dir yandex-cript:/.rclone-backup/`date +%Y%m%d.%H%M%S`
  backup:
    deps: [backup-onedrive, backup-dropbox, backup-yandex]

  web:
    cmds:
      - rclone rcd --rc-web-gui

  export:
    cmds:
      - node export.js
  import:
    cmds:
      - node import.js
